### ISSUE TITLE
strict_type support is all broken

### ISSUE THREAD

**Issue by hopeseekr** [exakat/exakat#104]
There is nothing wrong with `<?php declare(strict_types=1);` but exakat reports: 
![image](https://user-images.githubusercontent.com/1125541/59566704-2fb59900-9029-11e9-814b-9098130ae663.png)

**Comment by exakat** [comment]
So, declare ticks/encoding don't behave like declare strict_types : 
PHP Fatal error:  strict_types declaration must not use block mode in test.php on line 3
No block declaration either.

I have a quick patch for 1.8.4, and it needs some more review.

**Comment by exakat** [comment]
This is not appearing anymore in the current version (1.9.7).
