### ISSUE TITLE
Check specific part of code only

### ISSUE THREAD

**Issue by shyim** [exakat/exakat#107]
I want to run exakat on an extension. But if I run only exakat about the plugin, I get multiple missing class issues.
But if I run the complete project with the extension, I get the also issues for other files.
I tested it with ignore_directory, but its not the same thing what I need here. Phpstan has for such issues an autoload file flag

**Comment by exakat** [comment]
When you are using the Ambassador report (for example), there is a faceted engine in the issues, that allow you to filter by file and analysis. 

When you are using the Text report (or another generic report), you can filter with the file name and its path. 

What is your configuration with ignore_dirs and include_dirs ?

**Comment by shyim** [comment]
What you mean its just a filter of the output. When your extension has only 2 php files, you have to scan the entire PHP Project with 140 Composer dependencies.
It's a bad workaround.

I have added the project as include_dirs and ignore_dirs. Cause I want that exakat checks that code, but don't list it in the report. 

Is there any option to hey, when you don't find classes search there.
