### ISSUE TITLE
False positive on Continue Is For Loop

### ISSUE THREAD

**Issue by francislavoie** [exakat/exakat#110]
https://exakat.readthedocs.io/en/latest/Rules.html#continue-is-for-loop

In a situation where a switch statement has a for/foreach loop inside of it, this warning is still emitted although it's actually a non-issue (PHP 7.3 doesn't emit the error and it runs just fine).

I didn't try this minimal case on its own yet. Is there a playground thing somewhere I can muck around with exakat? What's a good way of trying some one-off tests like this?

It seems to come up in cases similar to this in my codebase.

```php
<?php

switch ($bar) {
    case 'baz':
		foreach (['thing', 'thing2'] as $thing) {
			if ($thing === 'thing2') {
				continue;
			}
		}
		break;
}
```

```php
<?php

foreach (['thing', 'thing2'] as $thing) {
	switch ($bar) {
    	case 'baz':
			if ($thing === 'thing2') {
				continue 2;
			}
			break;
	}
}
```

**Comment by francislavoie** [comment]
@dseguy so is this fixed by https://github.com/exakat/exakat/commit/baf6ec06ee4956b9c44b962aa8fed8e5f0652f98 ?

I see my test case examples in the commit 😁

**Comment by exakat** [comment]
Yes, examples were perfect to reproduce and fix. Thanks :) 
Waiting for your feedback

**Comment by francislavoie** [comment]
Seems fixed to me :smile:
