### ISSUE TITLE
Some links are broken in the reports

### ISSUE THREAD

**Issue by francislavoie** [exakat/exakat#111]
On the `Online docs` links in the `analyses_doc.html`, some anchors in the links aren't correctly formed.

e.g. Incorrect:
`https://exakat.readthedocs.io/en/latest/Rules.html#usort-sorting-in-php-7.0`

vs Correct:

`https://exakat.readthedocs.io/en/latest/Rules.html#usort-sorting-in-php-7-0`

note the `-` vs the `.` between `7-0`

**Comment by francislavoie** [comment]
Also happens with words like `don't`, `'` should become `-`

**Comment by exakat** [comment]
Thanks for the list of errors and their fix.
It is now fixed in the source, and will be available in the next version 1.9.0.
