### ISSUE TITLE
False positive on Failed Substr Comparison

### ISSUE THREAD

**Issue by francislavoie** [exakat/exakat#113]
https://exakat.readthedocs.io/en/latest/Rules.html#failed-substr-comparison

In my code, I have `substr($value, 0, 1) == "\""`. I think that this analyzer isn't taking into account escaped chars when calculating the string length.

I think I can just change it to `'"'` though.

**Comment by exakat** [comment]
You are twice right : \" was mistaken with a longer string. This and some sequences are now under control. 

And you can also skip the \ with single quotes.

Fix is coming up in 1.9.0
