### ISSUE TITLE
False positive on Should Use SetCookie()

### ISSUE THREAD

**Issue by francislavoie** [exakat/exakat#114]
https://exakat.readthedocs.io/en/latest/Rules.html#should-use-setcookie

I have code such as:

```
<?php
header('Access-Control-Allow-Headers: Access-Control-Allow-Origin, Content-Type, Content-Length, Content-Disposition, Date, Expires, Last-Modified, Set-Cookie');
```

I think this gets flagged because it contains `Set-Cookie`, but the intent is not to actually set a cookie here. `Access-Control-Allow-Headers` is just a whitelist of header names.

**Comment by exakat** [comment]
Indeed, this is a bug. 

Spotted and filtered. 

Will be available in 1.9.0 next monday.
