### ISSUE TITLE
Exakat docker image

### ISSUE THREAD

**Issue by ClementDuez** [exakat/exakat#116]
Hi,

Since July 19, the new docker image is broken
exakat extension don't work.

You only have the latest tag available.

**Comment by exakat** [comment]
Thanks for the feedback.

There is a new image, build 2 days ago.  Can you try it? 
[https://hub.docker.com/r/exakat/exakat/builds](https://hub.docker.com/r/exakat/exakat/builds)

Also, is there documentation to handle multiple tags on hub.docker.com  ?

**Comment by ClementDuez** [comment]
When you build `docker build --tag exakat/exakat:yourVersion .`
Then docker push exakat/exakat:yourVersion

And to tag an image 
docker tag ImageId exakat/exakat:yourVersion
Then push.

Thanks for the image, it works :)
