### ISSUE TITLE
compatibility_issues.html not being generated

### ISSUE THREAD

**Issue by catalin0608** [exakat/exakat#118]
Hey,

After running exakat, checking the page for compatibility i saw that when i click the warnings it's returning report/datas/compatibility_issues.html was not found, even though everything is running ok. 
Also in console reports that this is also not found report/datas/scripts/vendor/modernizr.js

Any clue ?

**Comment by catalin0608** [comment]
Ubuntu desktop 18.04.1
php exakat.php doctor output

exakat : 
    executable           : exakat.phar
    version              : 1.8.9
    build                : 973
    exakat.ini           : ./config/exakat.ini
    graphdb              : tinkergraph
    reports              : 
    rulesets             : CompatibilityPHP53,
                           CompatibilityPHP56,
                           CompatibilityPHP72,
                           CompatibilityPHP73,
                           Analyze,
                           Preferences,
                           Appinfo,
                           ClassReview,
                           Appcontent,
                           "Dead code",
                           Security,
                           Custom,
                           Coding Conventions,
                           Top10
    extra rulesets       : 
    tokenslimit          : 10 000 000 000

PHP : 
    binary               : 7.3.7-2+ubuntu18.04.1+deb.sury.org+1
    memory_limit         : -1
    ext/curl             : Yes
    ext/hash             : Yes
    ext/phar             : Yes
    ext/sqlite3          : Yes
    ext/tokenizer        : Yes
    ext/mbstring         : Yes
    ext/json             : Yes
    ext/xmlwriter        : Yes
    ext/pcntl            : Yes
    pcre.jit             : Off (Must be off on PHP 7.3 and OSX)

java : 
    installed            : Yes
    type                 : OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
    version              : openjdk
    $JAVA_HOME           : 
    $JAVA_OPTIONS        : 

tinkergraph : 
    installed            : Yes (folder : /home/catalin/exakat/tinkergraph)
    host                 : 127.0.0.1
    port                 : 8182
    gremlin version      : 3.4.2

gsneo4j : 
    installed            : No (folder : tinkergraph)

folders : 
    projects folder      : Yes
    projects/test        : No
    projects/default     : No
    projects/onepage     : No

php52 : 
    configured           : No

php53 : 
    configured           : No

php54 : 
    configured           : No

php55 : 
    configured           : No

php56 : 
    configured           : Yes (/usr/bin/php5.6)

php70 : 
    configured           : No

php71 : 
    configured           : No

php72 : 
    configured           : Yes (/usr/bin/php7.2)

php73 : 
    configured           : Yes (/usr/bin/php7.3)

php74 : 
    configured           : No

php80 : 
    configured           : No

**Comment by exakat** [comment]
This is when running the Migration 7.3 and 7.4 report, right ? 

This has been spotted and fixed this week, will be available next monday.

**Comment by catalin0608** [comment]
I run it for a code written in php5.6 to check compatibility to version 7.0/7.1/7.2/7.2/7.4. It shows me that warnings are detected but because the page compatibility_issues.html is not generated i can't see where exactly in my code are the issues no matter on which version i check the compatibility page.

Thank you for your reply. Waiting for the fix.

**Comment by exakat** [comment]
compatibility_issues.html was omitted in the generation. This is fixed in 1.9.0 (later today)
