### ISSUE TITLE
False positive on "No array_merge() In Loops"

### ISSUE THREAD

**Issue by philippechevieux** [exakat/exakat#119]
Hi, 

For this rule : https://exakat.readthedocs.io/en/latest/Rules.html#no-array-merge-in-loops

Analyzer report code where there is no array_merge(), for exemple : 
```
foreach ($pages as $key => $page) {
     $pages[$key] = someValueCaculated...
}
```

Here is my exakat version : Version : 1.8.7 - Build 962 - Tue, 09 Jul 2019 04:19:02 +0000

**Comment by exakat** [comment]
Hi philippechevieux,

Looking at the code above, there is no mention of array_merge(). `someValueCaculated` is an expression, and Exakat will follow functions/methods calls to their definition, and check that array_merge is used there too. Check the (simplistic) code below. 

`
foreach ($pages as $key => $page) {
     $pages[$key] = $x->foo($page);
}

class bar {
  private $x = array(); 
 function foo($page) {
   $this->x = array_merge($this->x, $page);
 }
}
`

**Comment by philippechevieux** [comment]
Thanks you for your answer. Indeed there was an array_merge() in a function call by `someValueCalculated`
