### ISSUE TITLE
Detect all paths in exakat

### ISSUE THREAD

**Issue by Rivendall** [exakat/exakat#13]
Hello
I research about static code analyzers. I want to understand, how to work them. Specially, Parse after analysis and detect patch in php code. I know, php parser not be able to recognize include, require and etc expression. I want to know, how dose your program recognize path? Or is it need?
Did you use any library or tools? or did you develop this part in your app?
How dose exakat detect all paths in php code?
How about other tools?
Dose it need special libraries?

Thank you.

**Comment by exakat** [comment]
Hi Rivendall,

The files are detected early during Exakat analysis and then they are all used at the same time. This is slightly different from PHP execution, which include files as they are needed with include/require. 

This way, exakat avoids interpreting the Path to the file, as it may be dynamic. The analysis happends at the namespace level, not the file levels.
