### ISSUE TITLE
CE install instructions listed on exakat.io no longer work

### ISSUE THREAD

**Issue by christopherowen** [exakat/exakat#137]
https://www.exakat.io/en/exakat-community-edition/

**Comment by exakat** [comment]
Indeed, it was lagging.

It is now updated : https://www.exakat.io/en/exakat-community-edition/
Docs are more often updated : https://exakat.readthedocs.io/en/latest/Installation.html#id2 (and the whole section)

Video will need an update too.

**Comment by christopherowen** [comment]
awesome :)

may I recommend putting quotes around the URL in:

```
curl -o exakat.phar https://www.exakat.io/versions/index.php?file=latest
```

The question mark causes issues for the default shell in MacOS; zsh.

**Comment by christopherowen** [comment]
working with tinkerpop 3.4.7 instead of the recommended 3.4.6 allowed installation to continue on MacOS Big Sur.

**Comment by exakat** [comment]
Big sur : Good to know. Thanks
3.4.7 : OK, here too. 
Documentation : updated, both online and in the manual.
