### ISSUE TITLE
Idea - Sarif v2.1.0 support with external library

### ISSUE THREAD

**Issue by llaville** [exakat/exakat#151]
Hello Damien,

I'm author of a new PHP package that implement the full specification of SARIF v2.1.0

If you want to improve your Sarif Report (available since v2.1.8), perharps you can have a look on my PHP SDK version available at https://github.com/llaville/sarif-php-sdk

All API is fully documented including examples. 

Have a look (i.e) at 
- https://llaville.github.io/sarif-php-sdk/reference/message/#plaintext-example sarif output
- https://llaville.github.io/sarif-php-sdk/reference/message/#how-to-generate script to generate it 

Feedback are welcome !
Laurent

**Comment by exakat** [comment]
Hi Laurent,

good idea. This is now included in Exakat 2.3.0.
