### ISSUE TITLE
Object of class stdClass could not be converted to string error

### ISSUE THREAD

**Issue by mrgeneralgoo** [exakat/exakat#18]
Object of class stdClass could not be converted to string error.

Error in Exakat\Analyzer\Php\ClassFunctionConfusion 37 line.

Bug in Exakat\Analyzer\Analyzer 415 and 434 line.

`$a = (array){new stdClass()}
var_dump($a);
array(1) {
  [0]=>
  object(stdClass)#235743 (2) {
    ["processed"]=>
    int(0)
    ["total"]=>
    int(0)
  }
}
`

I change `return array($result);` to `return json_decode(json_encode($result),true);` is ok.

PHP used	7.1 (7.1.1)
Exakat version	0.10.2 ( Build 555)

**Comment by exakat** [comment]
Thanks for the report. I think this is fixed in the upcoming 0.10.5 version. 
Any clue how to replicate this ?

**Comment by exakat** [comment]
This analysis has been refactored with version 0.12.x. 

I'll close it until more information.
