### ISSUE TITLE
help is not lisiting all the commands

### ISSUE THREAD

**Issue by Grummfy** [exakat/exakat#19]
Hello,
when you look at the documentation you see that there is a lot of command http://exakat.readthedocs.io/en/latest/Commands.html but 4 are listed in helps.

Suggestions:
* list all command in help
* add a link to the documentation inside help command
* do both ;)

**Comment by exakat** [comment]
This help should not flood user with too much information. 

Added a link to the documentation. 

Fixed in 1.2.4
