### ISSUE TITLE
error on report codesniffer

### ISSUE THREAD

**Issue by Grummfy** [exakat/exakat#20]
Hello when I want to create the codesniffer report I got an error

Error : Format 'Codesniffer' doesn't exist. Choose among : Ambassador, Devoops, Text, Xml, Uml, PhpConfiguration, PhpCompilation, Inventories, Clustergrammer, FileDependencies, FileDependenciesHtml, ZendFramework, RadwellCode, Codesniffer, FacetedJson, Json, OnepageJson, Codacy 
on file phar:///usr/src/exakat/exakat.phar/library/Exakat/Tasks/Report2.php
on line 49

**Comment by EdwinKortman** [comment]
It's case sensitive, try using:
`php exakat.phar report -p [project] -format CodeSniffer`
