### ISSUE TITLE
exacat v 0.10.8   running error on ubuntu

### ISSUE THREAD

**Issue by rvdruten** [exakat/exakat#21]
php exakat.phar doctor
exakat : 
    executable           : exakat.phar
    version              : 0.10.8
    build                : 571
    exakat.ini           : /home/rikvd4/exakat/config/exakat.ini
    reports              : Ambassador,
                           PhpConfiguration,
                           PhpCompilation,
                           RadwellCode,
                           ZendFramework
    themes               : CompatibilityPHP70,
                           CompatibilityPHP71,
                           CompatibilityPHP72,
                           Analyze,
                           Preferences,
                           Appinfo,
                           Appcontent,
                           "Dead code",
                           Security,
                           Custom

PHP : 
    binary               : 7.1.4-1+deb.sury.org~xenial+1
    ext/curl             : Yes
    ext/hash             : Yes
    ext/phar             : Yes
    ext/sqlite3          : Yes
    ext/tokenizer        : Yes
    ext/mbstring         : Yes
    ext/json             : Yes

java : 
    installed            : Yes
    type                 : Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
    version              : java
    $JAVA_HOME           : 

neo4j : 
    version              : Neo4j 2.3.9
    MaxPermSize          : 512m
    port                 : 7474
    authentication       : Not enabled
    gremlinPlugin        : Configured.
    gremlinJar           : neo4j-gremlin-3.2.0-incubating.jar
    scriptFolder         : Yes
    pid                  : 1799
    running              : No
    $NEO4J_HOME          : 
    $NEO4J_HOME / config : Different

folders : 
    config-folder        : Yes
    config.ini           : Yes
    projects folder      : Yes
    projects/test        : No
    projects/default     : No
    projects/onepage     : No

PHP 5.2 : 
    configured           : No

PHP 5.3 : 
    configured           : No

PHP 5.4 : 
    configured           : No

PHP 5.5 : 
    configured           : No

PHP 5.6 : 
    configured           : No

PHP 7.0 : 
    configured           : No

PHP 7.1 : 
    configured           : Yes (/usr/bin/php)
    version              : 7.1.4-1+deb.sury.org~xenial+1
    short_open_tags      : Off
    timezone             : 
    tokenizer            : Yes
    memory_limit         : -1

PHP 7.2 : 
    configured           : No

---------------------------------
Error running 

Error : Error during Gremlin query : 'org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script6.groovy: 1: unexpected token: a @ line 1, column 5.
   def a-407714139() { 
       ^

1 error
'.
Query : a-407714139 = a-407714139();
g.V().hasLabel("Identifier")
     .where( __.in("DEFINITION", "NEW", "USE", "NAME", "EXTENDS", "IMPLEMENTS", "CLASS", "CONST", "CONSTANT", "TYPEHINT", "FUNCTION", "GROUPUSE", "SUBNAME", "PROPERTY").count().is(eq(0)) )  
     .filter{ it.get().value("code").toLowerCase() in a-407714139 }
     .sideEffect{ 
        fullnspath = "\\" + it.get().value("code").toLowerCase();
        it.get().property("fullnspath", fullnspath); 
      }

 
on file phar:///home/rikvd4/exakat/exakat.phar/library/Exakat/Graph/Gremlin3.php
on line 210

**Comment by dseguy** [comment]
Thanks for the report. I have an idea about the problem here.

**Comment by exakat** [comment]
This is fixed in version 0.11.0.
