### ISSUE TITLE
Analysing large files results in memory overflow

### ISSUE THREAD

**Issue by EdwinKortman** [exakat/exakat#23]
Hi!

I am using Exakat to analyse a large application with files going well over 8.000 lines. When I use normal settings for PHP (normal being memory_limit set to anything expect infinite) it results in an error when decoding the json from the curl result (https://github.com/exakat/exakat/blob/master/library/Exakat/Graph/Gremlin3.php#L196). A proposed solution would be using a library to read the result as a stream.
Something like https://github.com/salsify/jsonstreamingparser could be used.

What do you think of this solution?

Regards,

Edwin

**Comment by exakat** [comment]
I run Exakat on the Zend Framework 3 ( 450146 LOC) with 8Gb of RAM without a memory problem. 
Check if PHP has unlimited memory, which is the usual problem.

I take note of your suggestion. Looks interesting to read data and make this a generator. 
I'll see how I can adapt this in Gremlin3.php

**Comment by EdwinKortman** [comment]
In my case it didn't had unlimited memory which caused the unexpected error. Thanks for the response!
