### ISSUE TITLE
Question: Error in run exakat. 

### ISSUE THREAD

**Issue by Rivendall** [exakat/exakat#24]
Hello. 
I install exakat with phar and with git in windows. After, i run exakat but saw a lot of error. For example, error php version, sqlite3 ... . After solve, run any commands that there are in your document. 
errors are: 
```
$ php exakat doctor
exakat :
    executable           : exakat
    version              : 0.11.0
    build                : 575
    exakat.ini           : C:\exakat/config/exakat.ini
    reports              : Ambassador,
                           PhpConfiguration,
                           PhpCompilation,
                           RadwellCode,
                           ZendFramework
    themes               : CompatibilityPHP70,
                           CompatibilityPHP71,
                           CompatibilityPHP72,
                           Analyze,
                           Preferences,
                           Appinfo,
                           Appcontent,
                           "Dead code",
                           Security,
                           Custom

PHP :
    binary               : 7.0.6
    ext/curl             : Yes
    ext/hash             : Yes
    ext/phar             : Yes
    ext/sqlite3          : Yes
    ext/tokenizer        : Yes
    ext/mbstring         : Yes
    ext/json             : Yes

java :
    installed            : Yes
    type                 : Java(TM) SE Runtime Environment (build 1.8.0_102-b14)

    version              : java
    $JAVA_HOME           :

neo4j :
    installed            : Couldn't find the path to neo4j from the config/exaka
t.ini. Please, check it.

folders :
    config-folder        : Yes
    config.ini           : Yes
    projects folder      : Yes
    projects/test        : Yes
    projects/default     : No
    projects/onepage     : No

PHP 5.2 :
    configured           : No

PHP 5.3 :
    configured           : No

PHP 5.4 :
    configured           : No

PHP 5.5 :
    configured           : No

PHP 5.6 :
    configured           : No

PHP 7.0 :
    configured           : No

PHP 7.1 :
    configured           : No

PHP 7.2 :
    configured           : No

```
How can i correct them? 
and dose exakat detect security vulnerability? (sqli, xss ...)

Thank you.

**Comment by exakat** [comment]
Hi Rivendall. 

At that point, windows or not, you're missing the installation of Neo4j. 

I have not attempted to install Neo4j and gremlin 3 on Windows, so you probably need some experience to do that. 
The installation instructions for Linux are there : http://exakat.readthedocs.io/en/latest/Installation.html#quick-installation-with-debian-ubuntu

May be you can replicate and adapt them. 

Also, I expect exakat to be incompatible due to the usage of 'shell_exec' in the code. 
Can you run : 

php exakat.phar files init -p sculpin -R https://github.com/sculpin/sculpin.git -v 

It may report some errors.

**Comment by exakat** [comment]
Also, join the slack channel (exakat.slack.com) and I may be able to help you directly.

**Comment by Rivendall** [comment]
Thank you. Please add me in channel.

**Comment by jhstone78** [comment]
I am having the same issue with the neo4j connection on windows: "Couldn't find the path to neo4j from the config/exakat.ini. Please, check it."  Why is the neo4j_folder required when it has the host info and credentials?

**Comment by exakat** [comment]
This bug is not relevant anymore, since we moved from neo4j to gremlin-server.
