### ISSUE TITLE
 Error during Gremlin query

### ISSUE THREAD

**Issue by Rivendall** [exakat/exakat#25]
Hello
After run exakat for some code, for example phpmyadmin, some times we get error for gremlin. 

```
Error : Error during Gremlin query : 'Failure to begin transaction'.
Query : g.V().count();
 
on file /exakat/exakat.phar/library/Exakat/Graph/Gremlin3.php
on line 201
```
How can i fix them?

**Comment by exakat** [comment]
Hi Rivendall,

That looks like a connexion problem to Neo4j.
The best is to restart (or simply kill) the neo4j database, and start exakat again (Exakat will start neo4j if needed).

cd neo4j; 
./bin/neo4j start  <- This will display the neo4j process number
kill -9 <PID>
cd ..
php exakat.phar project -p <projectname>

**Comment by Rivendall** [comment]
Hello exakat, 
Thank you for answer. 
I run your command for neo4j, but I had a lot of error in some code. For Example, When my test code was very large, I hade errors. 
error 1: 
`
Error while running the Analyze Analyze ----------------------------------------------------------------------------------------------------------------------------------] 0.27% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze Appinfo ----------------------------------------------------------------------------------------------------------------------------------] 0.36% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze Security ---------------------------------------------------------------------------------------------------------------------------------] 2.94% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP54 -----------------------------------------------------------------------------------------------------------------------] 1.79% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP55 -----------------------------------------------------------------------------------------------------------------------] 1.92% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP56 -----------------------------------------------------------------------------------------------------------------------] 2.04% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze Appcontent -------------------------------------------------------------------------------------------------------------------------------] 2.50% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze Dead code --------------------------------------------------------------------------------------------------------------------------------] 2.33% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP53 -----------------------------------------------------------------------------------------------------------------------] 1.67% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP70 -----------------------------------------------------------------------------------------------------------------------] 2.04% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP71 -----------------------------------------------------------------------------------------------------------------------] 1.67% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP72 -----------------------------------------------------------------------------------------------------------------------] 4.17% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze Preferences ------------------------------------------------------------------------------------------------------------------------------] 6.67% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while building Ambassador in Ambassador 
No results database was found for project 'vtiger'.
Run php exakat.phar project -p vtiger first

Trying next report
Error while building Devoops in Devoops 
No results database was found for project 'vtiger'.
Run php exakat.phar project -p vtiger first

Trying next report
`

or: 

`Error while running the Analyze Analyze ----------------------------------------------------------------------------------------------------------------------------------] 0.27% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze Appinfo ----------------------------------------------------------------------------------------------------------------------------------] 0.36% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze Security ---------------------------------------------------------------------------------------------------------------------------------] 2.94% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP54 -----------------------------------------------------------------------------------------------------------------------] 1.79% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP55 -----------------------------------------------------------------------------------------------------------------------] 1.92% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP56 -----------------------------------------------------------------------------------------------------------------------] 2.04% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze Appcontent -------------------------------------------------------------------------------------------------------------------------------] 2.50% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze Dead code --------------------------------------------------------------------------------------------------------------------------------] 2.33% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP53 -----------------------------------------------------------------------------------------------------------------------] 1.67% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP70 -----------------------------------------------------------------------------------------------------------------------] 2.04% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP71 -----------------------------------------------------------------------------------------------------------------------] 1.67% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze CompatibilityPHP72 -----------------------------------------------------------------------------------------------------------------------] 4.17% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while running the Analyze Preferences ------------------------------------------------------------------------------------------------------------------------------] 6.67% 00:00:00    
Error during Gremlin query : ''.
Query : 

Trying next analysis
Error while building Ambassador in Ambassador 
No results database was found for project 'vtiger'.
Run php exakat.phar project -p vtiger first

Trying next report
Error while building Devoops in Devoops 
No results database was found for project 'vtiger'.
Run php exakat.phar project -p vtiger first

Trying next report`

Thank you.

**Comment by dseguy** [comment]
The analyzed project is not the same as the requested one : "osclass" / "". You probably want to use  -p .

This happens when Neo4j gets stuck and can't restart.  When this happens, try this : 
+ cd neo4j
+ ./bin/neo4j start 
[Neo4j mentions a PID that is already running, though it won't stop. Get that PID]
+ kill -9 [pid] 
+ cd ..
+ php exakat cleandb -Q 

Then run the project again.

**Comment by exakat** [comment]
This is probably fixed or changed since we moved from neo4j to gremlin-server.
