### ISSUE TITLE
"preg_replace with option e" does not match properly

### ISSUE THREAD

**Issue by NicoHaase** [exakat/exakat#26]
Analyzer/Structures/pregOptionE.php matches in out project for the following two expressions, even if that should not be the case:

`$txt = preg_replace("/<head>.+?<\\/head>/si", '', $txt);`
`$txt = preg_replace("/<style[^>]?>.+?<\\/style>/si", '', $txt);`

The following line does not trigger, even if I do not see much of a difference:
` $txt = preg_replace("/<script[^>]?>.+?<\\/script>/si", '', $txt);`

**Comment by dseguy** [comment]
Fixed in 0.12.2 version. 

Thanks :)

**Comment by NicoHaase** [comment]
Where can I find that version? The repository lists 0.12.0 as the latest version and no commits since June 27th

**Comment by exakat** [comment]
New version every monday. Today,s version is about to be released.

**Comment by NicoHaase** [comment]
The commit history in Github still lists exactly zero commits since June 27th....

**Comment by dseguy** [comment]
Just updated.
