### ISSUE TITLE
Improve documentation of "Strpos comparison"

### ISSUE THREAD

**Issue by NicoHaase** [exakat/exakat#27]
The report mentioned tons of "Strpos comparison"-issues, while only a small fraction was really issued by strpos calls. It would be good to improve the documentation such that it tells the user that this issue might also occur from other calls than strpos

**Comment by dseguy** [comment]
Hi Nicolas,

strpos() is definitely the poster child for this kind of issue, so I started with that name. Indeed, I need a way to both use strpos() (and make it easy to understand), and mention other functions are also vulnerable to this.

That said, the 0.12.1 version also omits preg_match() when preg_match uses literal as a regex : this way, the confusing null that preg_match returns is actually only seen in dev context. 

May be you have other examples of false-positive ?

**Comment by exakat** [comment]
I'm keeping this open until I add some examples in the docs, then I'll close it.

**Comment by exakat** [comment]
Examples added to documentation.
Good for publication with version 1.2.9, next monday.
