### ISSUE TITLE
Symfony controllers account for false negatives of "Static Methods Called From Object"

### ISSUE THREAD

**Issue by NicoHaase** [exakat/exakat#28]
In Symfony controllers, one can use `$this->get('service')` to fetch a service from the DI container. These calls are listed as issues of type "Static Methods Called From Object" in Exakat

**Comment by exakat** [comment]
"Static Methods Called From Object" has been upgraded in Exakat 0.12.2 (today's version). 
By default, it doesn't report methods, while it used to do that. That applied to Symfony and quite a number of of other cases. 

Upgrade to 0.12.2 and tell me about it.
