### ISSUE TITLE
Are there rules for high risk functions???

### ISSUE THREAD

**Issue by cyw3** [exakat/exakat#35]
High risk functions, such as phpinfo,eval,chroot,scandir,chgrp,chown,ini_alter,ini_restore,dl,pfsockopen,openlog,syslog,readlink,symlink,popepassthru,fsocket,fsockopen.

**Comment by exakat** [comment]
The current list of security issues is here : 

http://exakat.readthedocs.io/en/latest/Recipes.html#security

phpinfo : http://exakat.readthedocs.io/en/latest/Rules.html#phpinfo (added to security in 1.0.4)
Eval() Usage : http://exakat.readthedocs.io/en/latest/Rules.html#eval-usage (added to security in 1.0.4)

All the others are not reported as a security risk per se, as they also have legit usage. I think they should be coupled with injection (for example), to become a vulnerability. 

Then, the list may be completed with shell_exec, exec, ftp_, *_connect, *_query and quite a few others .

I'll do an inventory of them, so there is a list of sensitive operations to be aware of. And we'll review the security context for each of those function, case by case.

**Comment by cyw3** [comment]
Yes, I think it is necessary to focus sensitive functions.
