### ISSUE TITLE
Error when installing in Mac OS!!!

### ISSUE THREAD

**Issue by cyw3** [exakat/exakat#36]
When I install Exakat in Mac, I occur a problem below:
![image](https://user-images.githubusercontent.com/11549103/33005160-3f126a26-cd8a-11e7-9e63-70d67eea04b1.png)

![image](https://user-images.githubusercontent.com/11549103/33005208-7219a470-cd8a-11e7-938b-91af1ecf1acd.png)

**Comment by exakat** [comment]
HI

We met that problem last week too : it's a download problem on Gremlin server. It is consistently repeatable when it happens, (may be your case), but we haven't been able to repeat it here. 

It may be the host that should be distributing the .jar that is out of date. 

We're still looking for a solution here.

**Comment by exakat** [comment]
Also, note that this install is not compulsory. You may use exakat with the tinkergraph engine.

1) avoid the optional install
2) after 'exakat.phar doctor', open config/exakat.ini, and use 'graph="tinkergraph", (instead of graph="gsneo4j")
3) try again with sculpin example

**Comment by cyw3** [comment]
Can you provide a install package without the other install step so that I can use it directly???

**Comment by cyw3** [comment]
@exakat I wonder the difference between gsneo4j and tinkergraph in the exakat.

**Comment by exakat** [comment]
Installation : Just ignore the 'Optional' block of commands. 

Gremlin-server has different engines for storing graph databases. Neo4j and Tinkergraph are the two supported one.

Tinkergraph is faster, but memory-only, so better for smaller projects. GSneo4j is better suited for larger projects. 

There are plans to support other architectures than just Gremlin-Server, like Janusgraph.

**Comment by exakat** [comment]
@cyw3  : what version of OSX do you have ? 
It seems the problem is on 10.13, and I tested on 10.11 here.

**Comment by cyw3** [comment]
macOS Sierra

**Comment by exakat** [comment]
When the error log includes 'grapes', run those commands : 

rm -r ~/.groovy/grapes/
rm -r ~/.m2/

They remove some files for grapes (that will rebuild them later).
Then, run the installation for the plug in again.

**Comment by exakat** [comment]
Checking the progress on this issue. Is it still on ?
