### ISSUE TITLE
Sombrero!

### ISSUE THREAD

**Issue by szepeviktor** [exakat/exakat#39]
Please consider renaming the `datas` directory to data.
Thank you. :cactus: :horse: :boot:

**Comment by exakat** [comment]
In the Ambassador report ?

**Comment by szepeviktor** [comment]
I do not know what *Ambassador report* is.
The `datas` directory in the Exakat report.

**Comment by szepeviktor** [comment]
See https://github.com/exakat/exakat/search?utf8=%E2%9C%93&q=datas&type=

**Comment by szepeviktor** [comment]
Yes, in that report: http://exakat.readthedocs.io/en/latest/Reports.html#ambassador

**Comment by exakat** [comment]
this is changed, and will be available in version 1.9.2

**Comment by szepeviktor** [comment]
Thnx
