### ISSUE TITLE
ext-sqlite dependency

### ISSUE THREAD

**Issue by luispabon** [exakat/exakat#40]
I've been grepping exakat's source to see where exactly sqlite is used to not much avail - there are hundreds of references but most of them seem to be in tests. 

I'm trying to add exakat to projects without any db dependencies and where sqlite is not installed. Composer install fails as a result.

I'm aware of `--ignore-platform-reqs`. In this case it isn't an option.

**Comment by exakat** [comment]
Exakat has a dependency on sqlite3, not sqlite. 
It is used during init, loading and report generation, so it is compulsory. 

The exakat on packagist is old, though it requires sqlite3, not sqlite.

**Comment by exakat** [comment]
@luispabon : is this still an issue ?

**Comment by luispabon** [comment]
Nope, thank you
