### ISSUE TITLE
Installation Instruction Out of Date

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [exakat/exakat#41]
The installation instruction at : https://exakat.readthedocs.io/en/latest/Installation.html#requirements
specifically the ubuntu ones : https://exakat.readthedocs.io/en/latest/Installation.html#quick-installation-with-debian-ubuntu
suggest running `wget -O apache-tinkerpop-gremlin-server-3.2.6-bin.zip http://ftp.tudelft.nl/apache/tinkerpop/3.2.6/apache-tinkerpop-gremlin-server-3.2.6-bin.zip`
except that fails, becasuse the file apache-tinkerpop-gremlin-server-3.2.6-bin.zip, nolonger exists on the server. 
It appears it has been replaced by version 3.27.
The documentation needs to updated to reflect this version change

**Comment by exakat** [comment]
Thanks for the feedback. This has been changed and pushed. 
A few more minutes and it is public.

**Comment by exakat** [comment]
it's fixed and updated in the docs.
