### ISSUE TITLE
PHP binary for version 7.2 doesn't have the right middle version : "7.1.9" is provided

### ISSUE THREAD

**Issue by AaronZjs** [exakat/exakat#44]
Done
Array
(
    [notCompilable52] => N/C
    [notCompilable53] => N/C
    [notCompilable54] => N/C
    [notCompilable55] => N/C
    [notCompilable56] => N/C
    [notCompilable70] => N/C
    [notCompilable71] => 3
    [notCompilable72] => N/C
    [notCompilable73] => N/C
    [php] => 456
)

Error : PHP binary for version 7.2 doesn't have the right middle version : "7.1.9" is provided. Please, check config/exakat.ini 
on file phar:///Users/jun/Desktop/Tools/exakat/exakat.phar/library/Exakat/Phpexec.php
on line 216

please..thx

**Comment by AaronZjs** [comment]
please close the issues,is other problems

**Comment by exakat** [comment]
Closing the issue
