### ISSUE TITLE
Resolution of path to PHP runtime assumes PHP is the originating process

### ISSUE THREAD

**Issue by Synchro** [exakat/exakat#47]
If you make a fresh install of exakat and `chmod +x exakat.phar`, then use it with `./exakat.phar ...` instead of `php exakat.phar ...` , it assumes that the starting process is the current PHP runtime, and this results in an incorrect (and persistent) value in the config.ini file, in my case:

    php72 = /Users/marcus/Sites/exakat/./exakat.phar

which should have been:

    php72 = /usr/local/bin/php

This results in errors like this:

```
/usr/local/bin/php exakat.phar project -p myproject
Error : This PHP version (
 ________                 __              _
|_   __  |               [  |  _         / |_
  | |_ \_| _   __  ,--.   | | / ]  ,--. `| |-'
  |  _| _ [ \ [  ]`'_\ :  | '' <  `'_\ : | |
 _| |__/ | > '  < // | |, | |`\ \ // | |,| |,
|________|[__]`\_]\'-;__/[__|  \_]\'-;__/\__/


Exakat : @ 2014-2017 Damien Seguy.
Version : 1.1.9 - Build 704 - Mon, 19 Mar 2018 21:10:35 +0000
) is not valid for running Exakat. You need PHP 7.0 or later.

on file phar:///Users/marcus/Sites/exakat/exakat.phar/library/Exakat/Tasks/Load.php
on line 255
```

You can see that it's using the exakat version output instead of PHP's version output.

Inside the phar file it uses `/usr/bin/env php`, which does point to the correct runtime.

**Comment by exakat** [comment]
Finding the calling PHPbinary was based on $_SERVER['_'] while the most reliable source is the constant PHP_BINARY. 

This has been updated in Exakat 1.2.0.

Thanks for the bug report, Marcus.
