### ISSUE TITLE
Composer deps: requires guiguiboy/php-cli-progress-bar

### ISSUE THREAD

**Issue by luispabon** [exakat/exakat#48]
I'm trying to install exakat as a dev dependency through composer and it's currently failing as it requires `guiguiboy/php-cli-progress-bar:dev-master`. This conflicts with my `minimum-stability` (stable) config.

`php-cli-progress-bar` does have a 1.0 release, perhaps should require that instead? Or ditch in favour of something else as the project is abandoned and could become troublesome as PHP evolves and continues its deprecations.

**Comment by exakat** [comment]
I have been trying the 0.0.4 version, and it runs fine.  I've udpated the composer.json, so the required stability is 'stable' (sic).

Check out the 1.2.0 version.  

I don't see the point in moving to something else, as this current class is fine.

**Comment by luispabon** [comment]
:+1:

**Comment by exakat** [comment]
1.2.0 is still in the oven. 

Thanks for the bug report.

**Comment by exakat** [comment]
Closed last week.
