### ISSUE TITLE
No reports after execution using code from your documentation

### ISSUE THREAD

**Issue by kstalega** [exakat/exakat#49]
Hi,

I installed exakat on ubuntu 16.04. This  is report from exakat doctor: https://pastebin.com/FR7MVBfY The first issue which I had was that this command:
`php exakat.phar init -p sculpin -R https://github.com/sculpin/sculpin`
didn't clome given repository, so entered code dir and put git clone in terminal. After that I run:
`php exakat.phar project -p sculpin`
And there was few progress bar and script ended without error, but there is no dir like: projects/sculpin/report. Why report didn't generate?

Best regards,
KS

**Comment by kstalega** [comment]
OK, I don't know why but reports goes to directory like .report, so it was hidden by default. Now when I'm trying to open report and clicking index.html in projects/sculpin/.report I see something like this:
![fireshot capture 001 - exakat s php code review_ - file____home_konrad_documents_exak](https://user-images.githubusercontent.com/17795818/38470316-2b5c85bc-3b61-11e8-868a-613f0884f48d.png)

Why does it happen? What goes wrong? It seems like javascript is not working, but why?

**Comment by MojoJojo** [comment]
I can confirm this behavior. The html files just have template placeholders and the javascript is not working.

**Comment by exakat** [comment]
you may have run into an error with the Default Ambassador report. I have some fixes for this weeks's version, so one solution is to wait for tonight.

You may also check the docs for the other reports, and get something to review until then.

http://exakat.readthedocs.io/en/latest/Reports.html

**Comment by jamesburrow23** [comment]
I can confirm that I'm also having a similar problem.  I executed the analysis command and it took ~20 minutes to run.  The only output I received was ```27/27 [=====================>] 100.00% 00:00:00```.  After which I checked my projects folder and was missing the report.html file.  I was able to manually generate this file by running `php exakat.phar report -p <project_name> -format  Ambassador -file Ambassador` which outputted a report but the html file was missing charts and data left and right.  The issues page didn't contain anything but there were issues found (screenshot below)...Do you have any suggestions?  

I am running on Mac OSX 10.13.3 with  Java SE Development Kit 8u162

![image](https://user-images.githubusercontent.com/16297677/38690920-53458dd2-3e4d-11e8-8d3a-682cd55bfeff.png)



![image](https://user-images.githubusercontent.com/16297677/38690929-59658564-3e4d-11e8-8e3f-dd05b3ef156d.png)



### Also not the missing charts with javascript errors
![image](https://user-images.githubusercontent.com/16297677/38690966-7558c77c-3e4d-11e8-9709-a171fdb07c19.png)

**Comment by MojoJojo** [comment]
Seems to be fixed in the latest phar file. I was able to run the default ambassador report could view the reports (on Mac OS). Think most of the report is working except the "Recipe" dropdown/filter on the issues page. It shows as "Receipt" and the dropdown is empty.

**Comment by kstalega** [comment]
Ok, how can I update exakat? Just replace exakat.phar with newest version?

**Comment by MojoJojo** [comment]
@kstalega Just delete the folder containing Exakat installation and follow the installation steps again. Please double check you meet all the requirements. e.g. have JAVA_HOME setup properly and if its a large project make sure you have sufficient memory allocated to php in php.ini and to java via JAVA_OPTIONS.
Not sure if its required but I also installed Maven and Gradle locally and updated my PATH accordingly.

**Comment by exakat** [comment]
After installation, updating exakat is a simple replace for the phar. it will catch configuration and database at the location.

There is also exakat.phar upgrade -u too.

**Comment by exakat** [comment]
@kstalega  ping ?

**Comment by kstalega** [comment]
Everything works ok after update. Thank you all!

**Comment by soupli** [comment]
Anyone else experiencing this with the docker image 1.9.7 and 1.9.8?
Unfortunately i'm not getting any reports either. Audit is being run but no report(s)

Am i missing something? Thanks all!

```shell
$ docker run --rm -v $(pwd)/projects:/usr/src/exakat/projects exakat/exakat exakat project -v -p sculpin
```
```shell
Cleaning project
Cleaning project sculpin
removing datastore.sqlite
removing dump.sqlite
Removed 2 files
Recreating database
Search for external libraries
Processing files
'Updating sculpin/config.cache
Running project 'sculpin'
Running the following analysis : CompatibilityPHP53, CompatibilityPHP54, CompatibilityPHP55, CompatibilityPHP56, CompatibilityPHP70,
 CompatibilityPHP71, CompatibilityPHP72, CompatibilityPHP73, CompatibilityPHP74, Analyze, Preferences, Inventory, Performances, Appinfo
, Appcontent, Dead code, Security, Suggestions, ClassReview, Custom

Producing the following reports : Ambassador

Running files
Check composer
Searching for files
Found 158 files.
Check short tag (normal pass)
Check short tag (with directive activated)
Short tag OK
Removed 0 duplicates files
Check config files
Done
Cleaning DB
Restart gremlin server
start gremlin server 3.4.x
started gremlin server
Restarted in 14 rounds
started [353] in 10,512.59 ms
Loading with \Exakat\Loader\SplitGraphson
Init finalize================================================================>] 99.37% 00:00:02
loaded 2437 definitions
loaded nodes (duration : 1,477.62 ms)
Cleaning CSV
159/159 [====================================================================>] 100.00% 00:00:00
Start load final
add Returned void
290 added returned to Void
fixing Definitions for traits and interfaces
0 removed interface extends link
0 removed class extends link
0 removed class implements link
0 removed class implements link
fixing Fullnspath for Functions
0 fixed Fullnspath for Functions
Set 375 functioncall fallingback
Set 0 extension functioncall fallingback
spotFallbackConstants
Link constant definitions : skipping.
Fixed Fullnspath for Constants
13 SpotPHPNativeConstants
Created 0 isModified values
Created 49 isModified values with array append
Created 4 isModified values with unset
Created 4 isModified values with =>
Set 0 functions, constants and class with ignored_dir
End load final
Project loaded
Running the following rulesets : First
9/9 [========================================================================>] 100.00% 00:00:00
Initial dump
Removing old .dump.sqlite
Inited tables
Collecting data
Found 2 class changes
1 inclusions
0 extends for classes
0 extends for interfaces
149 typehint
0 traits
0 use
0 functioncall
0 constants
99 new
0 clone
110 static calls CPM
0 extends for classes
0 extends for interfaces
149 typehint
0 trait use
98 new
0 clone
109 static calls CPM
93 atoms
98 PHP functions
3 PHP constants
5 PHP interfaces
0 PHP traits
0 PHP classs
58 namespaces
139 classes
18 interfaces
0 traits
0 uses
551 methods
489 arguments
162 properties
17 constants
0 global constants
19 functions
20 arguments
Variables : 565
literalInteger : 291
literalFloat : 0
literalString : 1513
literalHeredoc : 17
literalArrayliteral : 132
Other Null : 1
Other Boolean : 1
Other Closure : 1
665 readability index
MethodsCounts : 18
ClassPropertyCounts : 11
ClassConstantCounts : 4
NativeCallPerExpression : 4
ClassTraits : 1
ClassInterfaces : 4
ClassChildren : 2
Definitions Stats
Class Depth : 3
Processing ruleset  : First
All 442 results saved for Functions/IsExtFunction
All 7 results saved for Interfaces/IsExtInterface
All 13 results saved for Constants/IsExtConstant
All 0 results saved for Traits/IsExtTrait
All 14 results saved for Functions/MarkCallable
Still 0 to be processed
Running the following rulesets : Dump
7/7 [========================================================================>] 100.00% 00:00:00
Running the following rulesets : CompatibilityPHP53, CompatibilityPHP54, CompatibilityPHP55, CompatibilityPHP56, CompatibilityPHP70, 
CompatibilityPHP71, CompatibilityPHP72, CompatibilityPHP73, CompatibilityPHP74, Analyze, Preferences, Inventory, Performances, Appinfo, 
Appcontent, Dead code, Security, Suggestions, ClassReview, Custom
92/92 [======================================================================>] 100.00% 00:00:00
```

**Comment by testdev4** [comment]
the same problem for me :( there is no report after scan completed
```
$ php exakat.phar upgrade -u
This is the latest version (2.0.2)
```

**Comment by rbrisita** [comment]
I have a similar problem. I am using version:
```
Version : 2.0.4 - Build 1016 - Mon, 18 Nov 2019 17:02:22 +0000
```
I waited about 8 hours for the scan to finish and no reports were generated and also no output other than this:
```
Error while running the ruleset Inventory.
Trying next ruleset.
Can't produce Ambassador format. There are 1 missing rulesets : Inventory.
```
I followed the exact instructions [here](https://exakat.readthedocs.io/en/latest/Installation.html#osx-installation-with-tinkergraph-3-4-3) with the option of the neo4j engine.  Here is a subset from the output of `php exakat.phar doctor`:
```
PHP :
    binary               : 7.3.11
    memory_limit         : -1
    short_open_tags      : Off
    ext/curl             : Yes
    ext/hash             : Yes
    ext/phar             : Yes
    ext/sqlite3          : Yes
    ext/tokenizer        : Yes
    ext/mbstring         : Yes
    ext/json             : Yes
    ext/xmlwriter        : Yes
    ext/pcntl            : Yes
    parallel_processing  : Yes
    pcre.jit             : On (Must be off on PHP 7.3 and OSX)

java :
    installed            : Yes
    type                 : Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
    version              : java
    $JAVA_HOME           :
    $JAVA_OPTIONS        :

tinkergraph :
    installed            : No (folder : tinkergraph)

gsneo4j :
    installed            : Yes (folder : /Users/rb/projects/php/security/exakat/tinkergraph)
    host                 : 127.0.0.1
    port                 : 8182
    gremlin version      : 3.4.3
    neo4j version        : 3.2.3
```
I would like to point out some confusing output:
```
...
pcre.jit             : On (Must be off on PHP 7.3 and OSX)
...
tinkergraph :
    installed            : No (folder : tinkergraph)
```
I did install tinkergraph but does gsneo4j supersede it? Also how do I turn off `pcre.jit` as it is suggested?
