### ISSUE TITLE
How to understand that is excluding files?

### ISSUE THREAD

**Issue by Mte90** [exakat/exakat#52]
I added different folders to ignore but in the log results as scanned.
There is a way to understand if the config is right? maybe is only scanning but ignoring them?

**Comment by exakat** [comment]
That needs more documentation, rather than a simple post here. Hold on.

**Comment by exakat** [comment]
New entry in the docs. 
http://exakat.readthedocs.io/en/latest/Configuration.html#id2

Entry in the FAQ : 
http://exakat.readthedocs.io/en/latest/FAQ.html#can-i-ignore-a-dir-or-a-file (and the next)

TBC

**Comment by Mte90** [comment]
As I can see is not very clear to understand what file are parsed.
Actually I have to work on config.ini, later run `project -p` etc wait 20 minutes or more and see from the report if the files was ignored.
Maybe a command to test the config or to see what files will be parsed is not bad.
Because the `load.log` show all the files parsed and there are stuff that I want that is ignored.

Actually to be sure of the scanning I am removing the files manually.

**Comment by Mte90** [comment]
Ok I got after the `project` command the datastore.sqlite has 2 tables, `files` and `ignoredFiles` with the list and my files as in the config.ini that I want to be ignored there aren't there...

```
ignore_dirs[] = /includes/freemius
ignore_dirs[] = /includes/Taxonomy_Core
ignore_dirs[] = /includes/CPT_Core
ignore_dirs[] = /includes/Widgets-Helper
ignore_dirs[] = /includes/CronPlus
ignore_dirs[] = /includes/Requirements
ignore_dirs[] = CMB2
ignore_dirs[] = i18n-module
ignore_dirs[] = WP-Dismissible-Notices-Handler
ignore_dirs[] = WP_Query_Multisite
ignore_dirs[] = tests
ignore_dirs[] = vendor
ignore_dirs[] = wp-config-test.php
ignore_dirs[] = index.php

include_dirs[] = /
```

I tried with relative path completed and now I was trying only the folder or filename to see what works.

**Comment by Mte90** [comment]
I am getting:
```
Error : Load task met an error : 'Warning : forgotten atom 22691 in /admin/includes/CMB2/includes/CMB2_JS.php : Ppp'
 
on file phar:///home/vagrant/exakat.phar/library/Exakat/Tasks/Load.php
on line 5144
```

But is specified:
```
ignore_dirs[] = /admin/includes/CMB2
```
