### ISSUE TITLE
How to exclude analyzers?

### ISSUE THREAD

**Issue by Mte90** [exakat/exakat#53]
I am not sure if this parameter is for that purpose because is not documented https://github.com/exakat/exakat/blob/master/projects/test/config.ini#L23 but I want that specific analyzers are not executed but I cannot find a documentation for that.

**Comment by exakat** [comment]
Hi @Mte90 

Don't use this : it s a specific configuration for one of the analyzers, and it still needs more work. 

Tonight's version (1.2.6) has support for selecting your analysis at Report time : exakat only exports the results you want. This is probably helping with your question. 

We are working on moving this usage earlier in the auditing process, so that will come in the next versions. I'll leave this open.

**Comment by Mte90** [comment]
I saw http://dist.exakat.io/ on the new version but there is no changelog and documentation about how to use this new feature.

**Comment by exakat** [comment]
Changelog is here : 
https://www.exakat.io/exakat-changelog/

There is usually a 'Exakat review' for each version, posted on the blog. And, I was swamped this week, so it's late and short for 1.2.6. But it's there.

**Comment by Mte90** [comment]
Ok now the changelog on the repo is updated :-)

What is the procedure to ignore analyzers? is a parameter in config.ini?

**Comment by exakat** [comment]
Yes, basically.

I upgraded the docs for this version (1.2.7) and I'll make a tutorial tomorrow on the subject.

In the mean time, http://exakat.readthedocs.io/en/latest/Configuration.html

**Comment by Mte90** [comment]
As I can see works like that I have to define what analyzers run but I want only to exclude few of them, in that way means a lot of job to do a list of all the analyzers because exakat have a lot of them.

**Comment by exakat** [comment]
I can see the need : it may be easier to remove a few analyzers, than configure a the (n -few) from an existing theme. I'd like to have a GUI for that, in fact : drag-and-drop themes or analysis from the left to the right, give a name, save to disk. That would be just fine!

I'll add an annex with the current themes's analyzers, so you can start from a copy/paste/edit. 

I have a longer tutorial ready, and I found some quirks that require a new version. Next monday, then.

**Comment by Mte90** [comment]
Ok I will wait for this list to c&p :-)

**Comment by Mte90** [comment]
any updates for this annex?

**Comment by exakat** [comment]
There : http://exakat.readthedocs.io/en/latest/Annex.html#themes-configuration

It's literally the LAST annex, at the bottom of all the manual. It takes quite a hike to reach there.

**Comment by Mte90** [comment]
Huge list is not enough indeed to explain how many testers are available 😂

**Comment by Mte90** [comment]
From less 1kb of config.ini now I have 37kb of this file...

Yes exclude will be the best solution also for the future to add automatically in case new analyzers without touch the config.

**Comment by Mte90** [comment]
any updates?
