### ISSUE TITLE
Add more description from analyzers

### ISSUE THREAD

**Issue by Mte90** [exakat/exakat#54]
![screenshot_2018-05-08 exakat s php code review](https://user-images.githubusercontent.com/403283/39750416-796a138a-52b5-11e8-9a0b-c188abcad83a.png)

That recap is very poor and looking on github there is more stuff https://github.com/exakat/exakat/blob/df1fbabcab7e67a611249b17ecf2beee96f45b22/human/en/Security/AnchorRegex.ini

I t is possible to add this stuff in the html report?

**Comment by dseguy** [comment]
Yes click on the blue book on the left, there is a full documentation with examples. 

The recap is made to be a one liner, indeed.

**Comment by Mte90** [comment]
You are right this is the right button not the blue + icon that is create confusion.
