### ISSUE TITLE
Error : No such loader as "Tinkergraph". Use one of SplitGraphson

### ISSUE THREAD

**Issue by abderrahmaneib** [exakat/exakat#55]
Hi,

When I try to scan initialised project, I have this error:
Error : No such loader as "Tinkergraph". Use one of SplitGraphson
 
on file phar:///<pathto>/exakat/exakat.phar/library/Exakat/Tasks/Load.php
on line 449

When checking the file I found that the loaderList array only contains SplitGraphson:
 private $loaderList = array('SplitGraphson');
 //'CypherG3', 'Neo4jImport', 'Janusgraph', 'Tinkergraph', 'GSNeo4j', 'JanusCaES', 'Tcsv',

Is this on purpose ?

How can I get this SplitGraphson ?

Thank you !

**Comment by Jimbolino** [comment]
same problem here.
When i run with default config it dies with the following message:
```Error : No such loader as "Tinkergraph". Use one of SplitGraphson
 
on file phar:///opt/exakat/exakat.phar/library/Exakat/Tasks/Load.php
on line 449
```

I've edited my config.ini and added:
```loader = "SplitGraphson";```

Now it dies with the following message:
```
Loading with SplitGraphson

Error : gremlin-php driver has thrown the following error : Connection refused 
on file phar:///opt/exakat/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 825
```

Probably the installation instructions need to be updated to fix this change.

**Comment by exakat** [comment]
Make sure that : 
graphdb = 'gsneo4j';

and NO 'loader' configuration is used : that means in config/exakat.ini and projects/*/config.ini 

Check with php exakat.phar doctor to be sure. 

I have cleaned some configuration mess for version 1.2.9, so that won't show up again.
Keep me posted if it stays.

**Comment by Jimbolino** [comment]
I've added to my config.ini:
`graphdb = 'gsneo4j';`
and still got the same errors

I've tried to install and get it running on 2 different machines:
Ubuntu 16.04 with the default openjdk-8-jre-headless (php 7.0.30)
Ubuntu 18.04 with the default openjdk-11-jre-headless (php 7.2.5)

ps. The installation instructions on the [main page](https://github.com/exakat/exakat) still mention the old tinkerpop.

**Comment by Jimbolino** [comment]
This commit: https://github.com/exakat/exakat/commit/4f67df8e159b6224ed13a0bf23abbe1bf1630ff5#diff-6696fccc9d51c8c06c819a4589f7cea4
deletes all the Loaders, only leaving the SplitGraphson. Not sure if it's related.

**Comment by Jimbolino** [comment]
Ok, stupid of me, i also had to uncomment these lines:
```
gsneo4j_host     = '127.0.0.1';
gsneo4j_port     = '8182';
gsneo4j_folder   = 'tinkergraph';
```
All is well and working now!

ps. is it normal that the gsneo4j server keeps running after the process is complete?
i've noticed a `sh: 1: kill: No such process` error in the gremlin.log

**Comment by exakat** [comment]
that kill happened while we moved from Gremlin 3.2 to 3.3, as they handled start/stopping the process in different way. This is fixed now.

Thanks for your contribution :)
