### ISSUE TITLE
Write in the report what Exakat version was used

### ISSUE THREAD

**Issue by Mte90** [exakat/exakat#56]
To check if everything is update can be helpful to have somewhere written with what version of exakat the report is generated.

**Comment by exakat** [comment]
Which report are you using ? 

The version and build is reported with Ambassador, Owasp or Drillinstructor (to name a few), as the HTML report allows for verbose information. Check the 'Annex' section.

On the other hand, Text or JSON is basically one report per line, and has no room for meta data.

May be the XML version could get that info.

Also, if anything like a standard format exists for reports, I'm intersted.

**Comment by Mte90** [comment]
Ok found in Annexes->Analyzer settings there is the version number. I was expecting that in the dashboard on `Audit date : 24-05-2018 10:15:02 - "Various Zak"` or near the logo in the footer.

**Comment by exakat** [comment]
Actually, "Various Zak" is an ID for the current report. It's different for each audit you run on code, so you can easily check which audit you are reading (or you can mention it to someone else).

Audits results may be different if you changed the code (git pull) or if you updated exakat (from last week), so this ID is made on purpose to differentiate them.

**Comment by Mte90** [comment]
Ok but I mean that the exakat version can be added in that label

**Comment by exakat** [comment]
I added it in Exakat 1.3.5.
