### ISSUE TITLE
General error : Project 'x' exists but has no code folder (). Aborting

### ISSUE THREAD

**Issue by flyingbono** [exakat/exakat#6]
Each time I run Exakat, on any project (including http://exakat.readthedocs.io/en/latest/Example.html), I got the folowing error :

Project 'x' exists but has no code folder (). Aborting

**Comment by flyingbono** [comment]
Also tested with :

php exakat init -p exakat -R https://github.com/exakat/exakat
php exakat project -p exakat

> Project 'exakat' exists but has no code folder (). Aborting

Any idea ??

**Comment by grolmih** [comment]
Hello, Exakat, you never answered this question....  and just closed this issue :( , i also have this problem, any suggestions? 

root@ubuntu:/home/user/exakat# php exakat.phar init -p testme -R projects/testproject/
root@ubuntu:/home/user/exakat# php exakat.phar project -p testme

Error : No code in project 'testme'
on file phar:///home/user/exakat/exakat.phar/library/Exakat/Tasks/Files.php
on line 57

**Comment by grolmih** [comment]
as an added info, the logs are not showing any useful information , and the sqlite database generated on disk has empty tables... maybe you could help with some info?

**Comment by hopeseekr** [comment]
I'm having this exact problem. Obviously the documentation is missing at least one important step!
