### ISSUE TITLE
Can't produce Ambassador format. There are 17 missing themes

### ISSUE THREAD

**Issue by Bavragor** [exakat/exakat#62]
No reports at the moment, any suggestions on how to fix this?
I am using exakat 1.3.0 - Build 756 - Thu, 07 Jun 2018 16:37:14 +0000 as phar.

Thanks for your help in advance. :)

**Comment by Bavragor** [comment]
Complete error:

Can't produce Ambassador format. There are 17 missing themes : CompatibilityPHP53, CompatibilityPHP54, CompatibilityPHP55, CompatibilityPHP56, CompatibilityPHP70, CompatibilityPHP71, CompatibilityPHP72, CompatibilityPHP73, Analyze, Preferences, Performances, Appinfo, Appcontent, Dead code, Security, Suggestions, Custom.

**Comment by exakat** [comment]
I'm working on this. It happens randomly, so it's hard to reproduce. 

Although, I never had 17 of them... did the audit run ?

**Comment by Bavragor** [comment]
I did a screencast, which hopefully will help you reproducing it.
Also I am using latest mac os with php 7.2 installed via homebrew.

I guess with audit you mean the first step from the screencast?

![exakat](https://user-images.githubusercontent.com/7630518/41657207-e9d19f5e-7492-11e8-93fd-92507e1718cc.gif)

**Comment by exakat** [comment]
Thanks for the screen cast. That's a lot of effort for a bug report.

I do see that exakat runs the first set of analysis, and then, stop. There should be several more progressbar before the report. So, it actually stopped.

At that point, the installation is OK, but the phar met a bug. Can you update to this week's version ? 1.3.3  and run the same.
