### ISSUE TITLE
Error: gremlin-php driver : Connection refused 

### ISSUE THREAD

**Issue by svdubovik** [exakat/exakat#63]
Hello,
when I run Exakat,  I receive the next error:

```
Error : gremlin-php driver has thrown the following error : Connection refused 
on file phar:///usr/src/exakat/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 845
```

I receive this error also when I use docker container

Verbose log

```
Cleaning project
Cleaning project nlptools
removing log
removing datastore.sqlite
Removed 1 files
Recreating database
Search for external libraries
Processing files
No files to process. Aborting
Running project 'nlptools'
Running the following analysis : CompatibilityPHP53, CompatibilityPHP54, CompatibilityPHP55, CompatibilityPHP56, CompatibilityPHP70, CompatibilityPHP71, CompatibilityPHP72, Analyze, Preferences, Appinfo, Appcontent, "Dead code", Security, Custom, CompatibilityPHP73, Inventory, Performances, Dead code, Suggestions
Producing the following reports : Ambassador
Cleaning DB
start gremlin server 3.3.x
started gremlin server
Restarted in 20 rounds
started [32] in 21,031.85 ms
Running files
Check composer
Searching for files
Found the files
Check compilation for 71
Check short tag (normal pass)
Check short tag (with directive activated)
Short tag OK
Check config files
+ .git
Done
Array
(
    [notCompilable52] => N/C
    [notCompilable53] => N/C
    [notCompilable54] => N/C
    [notCompilable55] => N/C
    [notCompilable56] => N/C
    [notCompilable70] => N/C
    [notCompilable71] => 0
    [notCompilable72] => N/C
    [notCompilable73] => N/C
    [php] => 20
)
Loading with SplitGraphson

Error : gremlin-php driver has thrown the following error : Connection refused 
on file phar:///usr/src/exakat/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 845

```

**Comment by yaoweijie** [comment]
Hi svdubovik

I too is having the same issue

ubuntu@ip-10-138-2-145:~/exakat$ php exakat.phar project -p SomeProject

Error : gremlin-php driver has thrown the following error : Connection refused 
on file phar:///home/ubuntu/exakat/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 845

ubuntu@ip-10-138-2-145:~/exakat$

**Comment by kagarlickij** [comment]
I have the same, could it be related to the latest version of exakat only?

**Comment by yaoweijie** [comment]
Hi Guys

Anyways here's some of my observation so far. I realize that the gremlin server is not started so what I did was manually starting the gremlin server. But interestingly is once I execute the audit the error will once again appear, and the gremlin server will stop

![image](https://user-images.githubusercontent.com/8636612/41388299-dd69f998-6fbd-11e8-851f-775a9e9601c3.png)

**Comment by svdubovik** [comment]
The issue is related with incorrect config of Exakat. I've changed current config file to this
/Users/svyat/Dropbox/Documents/Work/Intell/el-9/exakat.ini

**Comment by yaoweijie** [comment]
Herm, interestingly I am getting another error after setting the above configuration

![image](https://user-images.githubusercontent.com/8636612/41696908-0330cbee-7549-11e8-94cb-5e0d80196941.png)

**Comment by girishi** [comment]
Hi , getting similar issue as shown below, unable to proceed , please suggest how to overcome

Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : Vertex with id already exists: 1
array (
  '@type' => 'g:Map',
  '@value' => 
  array (
    0 => 'stackTrace',
    1 => 'java.lang.IllegalArgumentException: Vertex with id already exists: 1
	at org.apache.tinkerpop.gremlin.structure.Graph$Exceptions.vertexWithIdAlreadyExists(Graph.java:1137)
	at org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph.addVertex(TinkerGraph.java:167)
	at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method.createVertex(Attachable.java:291)
	at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method.lambda$create$10(Attachable.java:149)
	at org.apache.tinkerpop.gremlin.structure.util.Attachable.attach(Attachable.java:63)
	at org.ap



------------
and the config of tinkergraph is shown as below , is it because of any version mismatch
tinkergraph : 
    installed            : Yes (folder : tinkergraph)
    host                 : 127.0.0.1
    port                 : 7474
    gremlin version      : 3.3.3

gsneo4j : 
    installed            : Yes (folder : /root/exakat/tinkergraph)
    host                 : 127.0.0.1
    port                 : 8182
    gremlin version      : 3.3.3
    neo4j version        : 3.2.3

**Comment by oxblue-rbollig** [comment]
I get stuck at the same point.  Not sure why this issue was closed.

Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : gremlin-groovy is not an available GremlinScriptEngine

 ===================  SERVER TRACE  ========================= 
array (
  'stackTrace' => 'java.lang.IllegalArgumentException: gremlin-groovy is not an available GremlinScriptEngine
	at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.registerLookUpInfo(CachedGremlinScriptEngineManager.java:95)
	at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.getEngineByName(CachedGremlinScriptEngineManager.java:58)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:263)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
',
  'exceptions' => 
  array (
    0 => 'java.lang.IllegalArgumentException',
  ),
)
 ============================================================ 
 
on file phar:///home/rabollig/Downloads/exakat/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 829

**Comment by aadityabagga** [comment]
I was able to reproduce this.

### Case 1: Install exakat, dont install optional neo4j - **_FAILS TO WORK_**

~~~~
mkdir exakat
cd exakat
wget -O exakat.phar http://dist.exakat.io/index.php?file=latest
wget -O apache-tinkerpop-gremlin-server-3.3.3-bin.zip http://dist.exakat.io/apache-tinkerpop-gremlin-server-3.3.3-bin.zip
unzip apache-tinkerpop-gremlin-server-3.3.3-bin.zip
mv apache-tinkerpop-gremlin-server-3.3.3 tinkergraph
rm -rf apache-tinkerpop-gremlin-server-3.3.3-bin.zip

php exakat.phar doctor
~~~~

~~~~
exakat : 
    executable           : exakat.phar
    version              : 1.5.1
    build                : 828
    exakat.ini           : config/exakat.ini
    graphdb              : gsneo4j
    reports              : Ambassador
    themes               : CompatibilityPHP53,
                           CompatibilityPHP54,
                           CompatibilityPHP55,
                           CompatibilityPHP56,
                           CompatibilityPHP70,
                           CompatibilityPHP71,
                           CompatibilityPHP72,
                           CompatibilityPHP73,
                           CompatibilityPHP74,
                           Dead code,
                           Security,
                           Analyze,
                           Preferences,
                           Appinfo,
                           Appcontent
    extra themes         : 
    tokenslimit          : 1 000 000

PHP : 
    binary               : 7.0.32-0ubuntu0.16.04.1
    memory_limit         : -1
    ext/curl             : Yes
    ext/hash             : Yes
    ext/phar             : Yes
    ext/sqlite3          : Yes
    ext/tokenizer        : Yes
    ext/mbstring         : Yes
    ext/json             : Yes
    ext/xmlwriter        : Yes

java : 
    installed            : Yes
    type                 : Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
    version              : java
    $JAVA_HOME           : 
    $JAVA_OPTIONS        : 

tinkergraph : 
    installed            : Yes (folder : tinkergraph)
    host                 : 127.0.0.1
    port                 : 7474
    gremlin version      : 3.3.3

gsneo4j : 
    installed            : Partially (missing neo4j folder : tinkergraph)

folders : 
    projects folder      : Yes
    projects/test        : No
    projects/default     : No
    projects/onepage     : No

php52 : 
    configured           : No

php53 : 
    configured           : No

php54 : 
    configured           : No

php55 : 
    configured           : No

php56 : 
    configured           : No

php70 : 
    configured           : Yes (/usr/bin/php7.0)
    version              : 7.0.32-0ubuntu0.16.04.1
    short_open_tags      : Yes
    tokenizer            : Yes
    assertions           : Yes
    memory_limit         : -1
    timezone             : 
    token_version        : Php72

php71 : 
    configured           : No

php72 : 
    configured           : No

php73 : 
    configured           : No

php74 : 
    configured           : No
~~~~

~~~~
$ php exakat.phar project -p myproject
sh: 1: cannot create db/tinkergraph.pid: Directory nonexistent

Error : gremlin-php driver has thrown the following error : Connection refused 
on file phar:///home/aaditya/Downloads/exakat/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 825

~~~~

Config not working: [exakat.ini.txt](https://github.com/exakat/exakat/files/2533650/exakat.ini.txt)


### Case 2: Install exakat, install optional neo4j - **_WORKED_**

~~~~
mkdir exakat
cd exakat
wget -O exakat.phar http://dist.exakat.io/index.php?file=latest
wget -O apache-tinkerpop-gremlin-server-3.3.3-bin.zip http://dist.exakat.io/apache-tinkerpop-gremlin-server-3.3.3-bin.zip
unzip apache-tinkerpop-gremlin-server-3.3.3-bin.zip
mv apache-tinkerpop-gremlin-server-3.3.3 tinkergraph
rm -rf apache-tinkerpop-gremlin-server-3.3.3-bin.zip

# Optional : install neo4j engine.
cd tinkergraph
./bin/gremlin-server.sh -i org.apache.tinkerpop neo4j-gremlin 3.3.3
cd ..

php exakat.phar doctor
~~~~

~~~~

exakat : 
    executable           : exakat.phar
    version              : 1.5.1
    build                : 828
    exakat.ini           : config/exakat.ini
    graphdb              : gsneo4j
    reports              : Ambassador
    themes               : CompatibilityPHP53,
                           CompatibilityPHP54,
                           CompatibilityPHP55,
                           CompatibilityPHP56,
                           CompatibilityPHP70,
                           CompatibilityPHP71,
                           CompatibilityPHP72,
                           CompatibilityPHP73,
                           CompatibilityPHP74,
                           Dead code,
                           Security,
                           Analyze,
                           Preferences,
                           Appinfo,
                           Appcontent
    extra themes         : 
    tokenslimit          : 1 000 000

PHP : 
    binary               : 7.0.32-0ubuntu0.16.04.1
    memory_limit         : -1
    ext/curl             : Yes
    ext/hash             : Yes
    ext/phar             : Yes
    ext/sqlite3          : Yes
    ext/tokenizer        : Yes
    ext/mbstring         : Yes
    ext/json             : Yes
    ext/xmlwriter        : Yes

java : 
    installed            : Yes
    type                 : Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
    version              : java
    $JAVA_HOME           : 
    $JAVA_OPTIONS        : 

tinkergraph : 
    installed            : Yes (folder : tinkergraph)
    host                 : 127.0.0.1
    port                 : 7474
    gremlin version      : 3.3.3

gsneo4j : 
    installed            : Yes (folder : tinkergraph)
    host                 : 127.0.0.1
    port                 : 7474
    gremlin version      : 3.3.3
    neo4j version        : 3.2.3

folders : 
    projects folder      : Yes
    projects/test        : No
    projects/default     : No
    projects/onepage     : No

php52 : 
    configured           : No

php53 : 
    configured           : No

php54 : 
    configured           : No

php55 : 
    configured           : No

php56 : 
    configured           : No

php70 : 
    configured           : Yes (/usr/bin/php7.0)
    version              : 7.0.32-0ubuntu0.16.04.1
    short_open_tags      : Yes
    tokenizer            : Yes
    assertions           : Yes
    memory_limit         : -1
    timezone             : 
    token_version        : Php72

php71 : 
    configured           : No

php72 : 
    configured           : No

php73 : 
    configured           : No

php74 : 
    configured           : No
~~~~

Config which worked: [exakat.ini.txt](https://github.com/exakat/exakat/files/2533655/exakat.ini.txt)

**Comment by philippechevieux** [comment]
Hi,

I've got this issue too on my project and i want to complete svdubovik response. 
Indeed this issue is related to a incorrect configuration of Exakat in : 

> "exakat/config/exakat.ini"

In my case this was to related to a incorrect path to PHP : 

**Before :**
> php71 = /usr/bin/php

**After :**
> php71 = /usr/local/bin/php

In case you're not sure of your PHP Path you can run : `which php` in a terminal. 
Maybe Exakat should provide an explicit message when this issue append ?
