### ISSUE TITLE
Warning : forgotten atom

### ISSUE THREAD

**Issue by Mte90** [exakat/exakat#66]
I get this:
```
Error : Load task met an error : 'Warning : forgotten atom 22691 in /admin/includes/CMB2/includes/CMB2_JS.php : Ppp'
 
on file phar:///home/vagrant/exakat.phar/library/Exakat/Tasks/Load.php
on line 5155
```

This is the file https://github.com/CMB2/CMB2/blob/trunk/includes/CMB2_JS.php and this was excluded (https://github.com/exakat/exakat/issues/52).

**Comment by exakat** [comment]
At the version of writing (1.3.6), this passes without a warning (independant file, or whole repository). 

Can you chech with a recent version ?

**Comment by Mte90** [comment]
As I can see the latest release is 1.3.5, i can try when the 1.3.6 will be available :-)

**Comment by Mte90** [comment]
tested with 1.3.9 and the problem persist

**Comment by Mte90** [comment]
any updates?

**Comment by Mte90** [comment]
I don't know I am not using anymore exakat.
