### ISSUE TITLE
End-of-central-directory signature not found.

### ISSUE THREAD

**Issue by ITwrx** [exakat/exakat#67]
as part of the installation instructions from the readme i run: 
`curl -o apache-tinkerpop-gremlin-server-3.2.6-bin.zip http://ftp.tudelft.nl/apache/tinkerpop/3.2.6/apache-tinkerpop-gremlin-server-3.2.6-bin.zip`

it finishes suspicioulsy quickly.

i run 
`unzip apache-tinkerpop-gremlin-server-3.2.6-bin.zip`

i get: 
`Archive:  apache-tinkerpop-gremlin-server-3.2.6-bin.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
`
thanks

**Comment by exakat** [comment]
This is a version problem. The mirror being used doesn't keep older version, and currently, Gremlin is 3.3.3 or (or 3.2.9). 

Please, upgrade to a more recent version of exakat, that uses Gremlin 3.3.3 : 

http://exakat.readthedocs.io/en/latest/Installation.html#osx-installation-with-tinkergraph-3-3-3

**Comment by ITwrx** [comment]
i didn't notice those instructions were for osx. i don't use osx. :) thanks for the answer. i successfully installed using composer instructions and modifying with latest version. though, if the readme has instructions for older versions that don't work, that might should be considered a bug in and of itself and was part of the reason i reported it. also, FWIW, i would have composer as the default instructions instead of osx.
