### ISSUE TITLE
Sculpin test scan is not successful.

### ISSUE THREAD

**Issue by ariefibis** [exakat/exakat#68]
![capture](https://user-images.githubusercontent.com/22467094/43179590-5b505340-8ff1-11e8-8cb8-a1b07047838f.PNG)

**Comment by exakat** [comment]
Check that projects/sculpin/code exists. 

In case it doesn't, remove projects/sculpin folder 
Then, call again the init, on one line : 
php exakat.phar init -p sculpin -R https://github.com/sculpin/sculpin 

The folder projects/sculpin/code should then exists.

**Comment by exakat** [comment]
Make sure that token_limit-100000000000000 uses an =, not a - (possibly a typo).

Once you have changed the limit in the config/exakat.ini, you may check it with the doctor : 

php exakat.phar doctor

`> php exakat.phar doctor
exakat : 
    executable           : exakat
    version              : 1.6.2
    build                : 854
    exakat.ini           : ./config/exakat.ini,
                           config/remotes.json,
                           config/themes.ini
    graphdb              : gsneo4j
    reports              : Ambassador
    themes               : mine2
    tokenslimit          : 1 000 000 000`
