### ISSUE TITLE
Error : Project too large (4107736 tokens found, 1000000 tokens limit). Check config/exakat.ini to change this limit

### ISSUE THREAD

**Issue by prateek-0490** [exakat/exakat#69]
Although I changed this limit but it doesn't solves the problem.

**Comment by exakat** [comment]
the limit is called 'token_limit'. You may change it in config/exakat.ini, for installation-wide effect, or project by project, in the projects/*/config.ini file. 

Which one did you use ?

**Comment by prateek-0490** [comment]
In config/exakat.ini
