### ISSUE TITLE
disable case sensitive for report name

### ISSUE THREAD

**Issue by 0x25** [exakat/exakat#86]
hello

it will be greate if text, owasp ... will be valide and not just Text, Owasp in report name

> php exakat.phar report -p dvwa -format owasp -f text
> 
> Error : Format 'owasp' doesn't exist. Choose among : Ambassador, AmbassadorNoMenu, Drillinstructor, Text, Xml, Uml, PlantUml, None, SimpleHtml, Owasp, PhpConfiguration, PhpCompilation, Favorites, Manual, Inventories, Clustergrammer, FileDependencies, FileDependenciesHtml, ZendFramework, CodeSniffer, Slim, RadwellCode, Grade, Weekly, Codacy, Scrutinizer, FacetedJson, Json, OnepageJson, Marmelab, Simpletable, Codeflower, Dependencywheel, Phpcity 
> on file phar:///opt/exakat/exakat.phar/library/Exakat/Tasks/Report.php
> on line 59

**Comment by exakat** [comment]
done. Will be available in version 1.6.2, next monday
