### ISSUE TITLE
'Coudln't reach the remote server'

### ISSUE THREAD

**Issue by WebDevBooster** [exakat/exakat#99]
When running the command `php exakat.phar extension list` it literally says: 
'Coudln't reach the remote server' (including the misspelling).
At the same time, the website exakat.io is online.

How can I fix the problem?

**Comment by exakat** [comment]
Hi webdevbooster

"Coudln't" was consistently used 4 times... It is now fixed (for 1.8.2).

Could you update to 1.8.1 (current) ?
